version: "3"
services:
  web:
    build: ./docker
    volumes:
      - .:/var/www/html
    ports:
      - 80
    environment:
      WEBROOT: /var/www/html/public/
      VIRTUAL_HOST: secret.test
      ENABLE_XDEBUG: 1
      PHP_IDE_CONFIG: serverName=secret
      XDEBUG_CONFIG: remote_host=docker.for.mac.localhost
      SKIP_COMPOSER: 1
    depends_on:
      - db
    networks:
      - default
      - proxy

  db:
    image: postgres:10.5
    volumes:
    - ./docker/sql-dumps:/docker-entrypoint-initdb.d
    ports:
      - 5432
    environment:
      POSTGRES_USER: "secret"
      POSTGRES_PASSWORD: ""

networks:
  proxy:
    external: true
